### ISSUE TITLE
[BUG] Parents' info missing from data files

### ISSUE THREAD

**Issue by dakrismeno** [lart-bangor/research-assistant#55]
**Describe the bug**
Parents' info seem to be compulsory (unless "N/A" is clicked):
![image](https://github.com/lart-bangor/research-assistant/assets/99651949/5f108793-b30d-4c92-8e26-ed9d7b49e324)

However, some data files only include partial info for parents. Here is an example of a file that only has "mother education", and nothing else:
![image](https://github.com/lart-bangor/research-assistant/assets/99651949/0a98ee20-a223-495f-a54d-d764c67b61a8)

**To Reproduce**
No idea....

**Comment by thatfloflo** [comment]
Thanks Marco, this needs a bit more investigating. I suspect what might be the case with the example here is that someone clicked the level of education for mother, then clicked N/A for mother, so all of them were empty except the level of education. That would make sense because the validation logic simply says "If N/A, treat these fields as optional", but will need to do a bit more just to double check. We might want to decide in these cases to remove any information that might have been entered before selecting N/A, do you have an opinion on that?

**Comment by dakrismeno** [comment]
Hi Florian,

That's a very good point, and likely the only possible explanation.

Yes, let's have a chat at some point about how to deal with cases like the one you describe.

Best wishes,

Marco

________________________________

**Comment by thatfloflo** [comment]
Just to confirm, the original behaviour described is simply the result of "N/A" for a parent, as per my comment above.
As of f370866 / #79, more fields are explicitly marked as `None`/`null` when they are NAed, and the parental data specifically is a list of up to two "parent info" datasets, which are omitted if NA, so it should be clear where the list has length 1 only one was provided, where it is length 0, none was provided.
